Data Editor Improvements for v1.3.1
- Comparmentalized the dataEditor.svelte into Svelte components.
- Implemented byte edits via the Data View.
- Revised file retention methods.
- Byte editing mode now determined by selection data.
- Implemented overwrite only editing restriction.
- Allow multi instances of the data editor to run at once.
- Implemented basic data profiling panel.
- Transitioned byte display from textarea to byte components.
- Implement partial search and replace.
- OmegaEdit upgrade to v0.9.70.

Closes apache#668
Closes apache#657
Closes apache#654
Closes apache#631
Closes apache#576
Closes apache#568
Closes apache#518
Closes apache#516
Closes apache#572
Closes apache#714
Closes apache#715

diff --git a/.github/workflows/CI.yml b/.github/workflows/CI.yml
--- a/.github/workflows/CI.yml
+++ b/.github/workflows/CI.yml
@@ -91,6 +91,7 @@ jobs:
       matrix:
         os: [macos-11, ubuntu-20.04, windows-2019]
         node: [ '14', '16' ]
+      fail-fast: false  # don't immediately fail all other jobs if a single job fails
     runs-on: ${{ matrix.os }}
     defaults:
       run:
@@ -115,5 +116,8 @@ jobs:
         if: runner.os == 'Linux'
       - run: yarn test
         if: runner.os != 'Linux'
+      - name: Check for Errors in macOS
+        run: tail -n 1000 '/Users/runner/Library/Application Support/omega_edit/'* && exit 1
+        if: failure() && runner.os == 'macOS'
       - name: Package
         run: yarn package
